### ISSUE TITLE
Compilation issues with Arduino IDE

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#24]
### Bug Report
- Description: It is not possible to compile version 2.0.0 Beta 1 with Arduino IDE
- Expected behaviour: Compilation working
- Actual behaviour: Errors such as:
```
ccVQHPBh.ltrans0.o:(.text+0xe32): undefined reference to `advi3pp::LCD::has_status()'
ccVQHPBh.ltrans0.o:(.text+0xe40): undefined reference to `advi3pp::LCD::set_status_PGM(char const*, signed char)'
ccVQHPBh.ltrans0.o:(.text+0x10a4): undefined reference to `advi3pp::LCD::refresh()'
ccVQHPBh.ltrans0.o:(.text+0x1be2): undefined reference to `advi3pp::LCD::set_status_PGM(char const*, signed char)'
```
- Steps to reproduce:
  - Open the project with Arduino IDE
  - Verify

**Comment by ghost** [comment]
I second this. As I have a different thermocouple arrangement, I need to fine tune the marlin software and recompile. I got the same errors as Andrivet reported.

**Comment by andrivet** [comment]
Temporary workaround: If you take the current content of the repository (https://github.com/andrivet/ADVi3pp-Marlin/archive/advi3++.zip), it compiles. Another workaround is to use a more recent version of Arduino IDE.

**Comment by andrivet** [comment]
I now compiles with Arduino IDE 1.8.5 or 1.9 (Beta)
